language: node_js
node_js:
  - "6"
before_install:
  - openssl aes-256-cbc -K $encrypted_80c49b52f7d7_key -iv $encrypted_80c49b52f7d7_iv -in travis_github_deploy_key.enc -out ~\/.ssh/travis_github_deploy_key -d
